blogapi/urls.py
from django.urls import path, re_path
from blogapi.views import login, article, comment, mood, user, file, apiEmail, history, sites

app_name = 'blogapi'
urlpatterns = [
    path('login', login.LoginView.as_view(), name='login'),  # 登录
    path('sign', login.SignView.as_view(), name='sign'),  # 注册
    path('article', article.ArticleView.as_view(), name='article'),  # 发布文章
    path('article/<int:nid>', article.ArticleView.as_view(), name='article'),  # 修改文章
    # 查看加密文章
    path('articlePwd/<int:nid>', article.ArticlePwdView.as_view(), name='articlePwd'),
    re_path(r'article/comment/(?P<nid>\d+)', comment.CommentView.as_view(), name='comment'),  # 发布评论
    # 评论点赞
    re_path('comment/digg/(?P<nid>\d+)', comment.CommentDiggView.as_view(), name='comment_digg'),
    # 文章点赞
    re_path('article/digg/(?P<nid>\d+)', article.ArticleDiggView.as_view(), name='article_digg'),
    # 文章收藏
    re_path('article/collect/(?P<nid>\d+)', article.ArticleCollectsView.as_view(), name='article_collect'),
    # 文章封面修改
    path('article/cover/<int:nid>', article.EditArticleCoverView.as_view(), name='EditArticleCover'),
    # 心情路由
    path('mood', mood.MoodView.as_view(), name='mood'),
    re_path(r'mood/(?P<nid>\d+)', mood.MoodView.as_view(), name='mood_delete'),  # 删除心情
    re_path(r'mood_comment/(?P<nid>\d+)', mood.MoodCommentView.as_view(), name='mood_comment_edit'),  # 修改心情
    # 修改密码
    path('edit_password', user.EditPasswordView.as_view(), name='editPassword'),
    # 修改头像
    path('change_avatar', user.EditAvatarView.as_view(), name='editAvatar'),
    path('upload/avatar', file.AvatarUploadView.as_view(), name='AvatarUpload'),
    path('upload/avatar/<int:nid>', file.AvatarUploadView.as_view(), name='AvatarDelete'),
    path('upload/cover', file.CoverUploadView.as_view(), name='CoverUpload'),
    path('upload/cover/<int:nid>', file.CoverUploadView.as_view(), name='CoverDelete'),
    # 粘贴上传
    path('paste_upload', file.PasteUploadView.as_view(), name='pasteUpload'),
    path('sendEmail', apiEmail.ApiEmailView.as_view(), name='sendEmail'),
    path('perfectInformation', user.EditUserInfoView.as_view(), name='perfectInformation'),
    path('cancelCollection', user.CancelCollectionView.as_view(), name='cancelCollection'),  # 取消收藏
    # 回忆录
    # 发布记录
    path('history/', history.HistoryView.as_view(), name='history'),
    # 编辑记录
    path('history/<int:nid>', history.HistoryView.as_view(), name='history'),
    # 网站导航
    # 添加网站标签
    path('addSiteTag/', sites.NavTagsView.as_view(), name='addSiteTag'),
    path('addSiteTag/<int:nid>', sites.NavTagsView.as_view(), name='EditOrDeleteSiteTag'),
    # 获取网站数据列表
    path('sites/', sites.NavView.as_view(), name='sites'),
    # 编辑网站数据
    path('sites/<int:nid>', sites.NavView.as_view(), name='EditSites'),
    # 用于动态获取网站标签
    path('siteTag', sites.NavTagView.as_view(), name='SiteTag'),
    # 网站点赞
    path('siteDigg/<int:nid>', sites.NavDiggView.as_view(), name='SiteDigg'),
    # 网站收藏
    path('siteCollect/<int:nid>', sites.NavCollectsView.as_view(), name='siteCollect'),
    # 意见反馈
    path('feedback', user.FeedBackView.as_view(), name='feedback'),
]

fengfengzhidao/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog01.urls')),
    path('api/', include('blogapi.urls')),
    # media配置
    # serve 静态文件开发试图 只用于本地开发 不推荐生产环境
    # 用户上传文件路由配置
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

blog01/views/backend.py
from django.shortcuts import render, redirect

from blog01.models import *
from blogapi.utils.permissions_control import is_super_fun




# Create your views here.
def backend(request):
    if not request.user.username:
        # 没有登录
        return redirect('/')
    user = request.user
    collect_query = user.collects.all()
    return render(request, 'backend/backend.html', locals())


@is_super_fun
def add_article(request):
    # 拿到所有的分类，标签
    tag_list = Tags.objects.all()
    # 拿到所有的文章封面
    cover_list = Cover.objects.all()
    category_list = Articles.category_choice
    print(category_list)
    return render(request, 'backend/add_article.html', locals())


# 编辑头像
def change_avatar(request):
    avatar_url = request.user.avatar.url.url
    avatar_list = Avatars.objects.all()
    for i in avatar_list:
        if i.url.url == avatar_url:
            avatar_id = i.nid
    return render(request, 'backend/change_avator.html', locals())


def reset_pwd(request):
    return render(request, 'backend/reset_pwd.html', locals())


@is_super_fun
def edit_article(request, nid):
    article_obj = Articles.objects.get(nid=nid)  # 获取到对应的文章
    tags = [str(tag.nid) for tag in article_obj.tag.all()]  # 拿到已经选择的标签
    tag_list = Tags.objects.all()
    cover_list = Cover.objects.all()  # 获取所有的封面
    category_list = Articles.category_choice
    return render(request, 'backend/edit_article.html', locals())


@is_super_fun
def admin_home(request):
    return render(request, 'backend/admin/admin_home.html')


# 头像列表
@is_super_fun
def avatar_list(request):
    avatar_all = Avatars.objects.all()
    return render(request, 'backend/avatar_list.html', locals())


# 文章封面
@is_super_fun
def cover_list(request):
    cover_query = Cover.objects.all()
    return render(request, 'backend/cover_list.html', locals())

templates/backend/add_article.html
{% extends 'backend/backend.html' %}
{% block css %}
	<link rel="stylesheet" href="/static/backend/css/add_article.css">
	<link rel="stylesheet" href="/static/editor-md/css/editormd.css">
{% endblock %}

{% block main %}
	<div class="add_article_action">
		{% block btn %}
			<el-button type="primary" @click="add_drawer=true">完善文章信息</el-button>
		{% endblock %}
	</div>
	{% block drawer %}
		<el-drawer
			title="添加文章"
			:visible.sync="add_drawer"
			direction="rtl">
			<div class="add_el_drawer_content">
				<el-collapse v-model="add_article_activeNames">
					<el-collapse-item title="文章标题" name="1">
						<el-input v-model="title" placeholder="文章标题"></el-input>
					</el-collapse-item>
					<el-collapse-item title="文章简介" name="2">
						<el-input
							type="textarea"
							:rows="5"
							resize="none"
							placeholder="请输入文章简介(默认截取正文前30字符)"
							v-model="abstract">
						</el-input>
					</el-collapse-item>
					<el-collapse-item class="category_tags" title="文章分类和标签" name="3">
						<el-select v-model="category_id" class="category" placeholder="请选择">
							{% for category in category_list %}
								<el-option
									label="{{ category.1 }}"
									value="{{ category.0 }}">
								</el-option>
							{% endfor %}


						</el-select>
						<el-select
							v-model="tags"
							multiple
							collapse-tags
							filterable
							allow-create
							default-first-option
							class="tags"
							style="margin-left: 20px;"
							placeholder="请选择文章标签">
							{% for tag in tag_list %}
								<el-option
									label="{{ tag.title }}"
									value="{{ tag.nid }}">
								</el-option>
							{% endfor %}
						</el-select>
					</el-collapse-item>
					<el-collapse-item title="文章封面" class="article_cover" name="4">
						<div class="left">
							<img src="/media/{{ cover_list|first }}" id="cover_img" >
						</div>
						<div class="right">
							<el-select popper-class="select_cover" @change="edit_select_cover" v-model="cover_id" placeholder="请选择文章封面">
								{% for cover in cover_list %}
									<el-option
										label="{{ cover.url.url }}"
										value="{{ cover.nid }}">
										<img src="{{ cover.url.url }}" alt="">
									</el-option>
								{% endfor %}
							</el-select>
						</div>
					</el-collapse-item>
					<el-collapse-item class="can_choose" title="文章可选设置" name="5">
						<el-switch
							style="display: block"
							v-model="recommend"
							active-color="#13ce66"
							inactive-color="#ff4949"
							active-text="上推荐"
							inactive-text="不上推荐">
						</el-switch>
						<el-switch
							style="display: block"
							v-model="pwd_active"
							active-color="#13ce66"
							inactive-color="#ff4949"
							active-text="加密"
							inactive-text="不加密">
						</el-switch>
						<el-input v-show="pwd_active" v-model="pwd" placeholder="请输入文章加密密码"></el-input>
					</el-collapse-item>
				</el-collapse>
				<div class="article_btn_list">
					<el-button type="success" @click="add_article">发布文章</el-button>
				</div>
			</div>
		</el-drawer>
	{% endblock %}

	<div id="editor">
		{% block textarea %}
			<textarea name="" id="" style="display: none"></textarea>
		{% endblock %}
	</div>
{% endblock %}
{% block js %}
	<script src="/static/blog01/js/jquery/jquery.min.js"></script>
	<script src="/static/editor-md/lib/marked.min.js"></script>
	<script src="/static/editor-md/lib/prettify.min.js"></script>
	<script src="/static/editor-md/editormd.min.js"></script>
	<script>
        $(function () {
            let theme = vue.theme
            var editor = editormd("editor", {
                width: "100%",
                height: "700",
                path: "/static/editor-md/lib/",
	            theme:theme,
	            previewTheme:theme,
            });
        });
	</script>
{% endblock %}

templates/backend/avatar_list.html
{% extends 'backend/backend.html' %}
{% load my_filter %}
{% block css %}
	<link rel="stylesheet" href="/static/viewer/css/viewer.css">
	<link rel="stylesheet" href="/static/backend/css/avatar_list.css">
{% endblock %}

{% block content %}
	<el-scrollbar style="height: 100px;margin-top: 20px">
		<ul class="avatar_list flex">
			{% for avatar in avatar_all %}
				<li class="{{ avatar|calculate_avatar }}">
					<div class="delete_icon flex center item_center">
						<i @click="avatar_cover_delete('{{ avatar.nid }}', 'avatar', $event)"
						   class="el-icon-delete-solid"></i>
					</div>
					<img src="{{ avatar.url.url }}" alt="">
				</li>
			{% endfor %}
		</ul>
	</el-scrollbar>
	<el-upload
		class="upload-demo"
		action="{% url 'blogapi:AvatarUpload' %}"
		multiple
		:headers="avatar_list_headers"
		:before-upload="avatar_list_upload"
		:on-success="avatar_list_success"
		list-type="picture">
		<el-button size="small" type="primary">点击上传</el-button>
		<div slot="tip" class="el-upload__tip">只能上传jpg/png文件，且不超过500kb</div>
	</el-upload>
{% endblock %}
{% block js %}
	<script src="/static/viewer/js/viewer.js"></script>
	<script>
        $('.avatar_list').viewer()
	</script>
{% endblock %}

templates/backend/cover_list.html
{% extends 'backend/backend.html' %}

{% load my_filter %}
{% block css %}
	<link rel="stylesheet" href="/static/viewer/css/viewer.css">
	<link rel="stylesheet" href="/static/backend/css/cover_list.css">
{% endblock %}
{% block content %}
	<el-scrollbar style="height: 300px;margin-top: 20px;">

		<ul class="cover_list flex">
			{% for cover in cover_query %}
				<li class="{{ cover|calculate_cover }}">
					<div class="delete_icon flex center item_center">
						<i @click="avatar_cover_delete('{{ cover.nid }}', 'cover', $event)" class="el-icon-delete-solid"></i>
					</div>
					<img src="{{ cover.url.url }}" alt="">
				</li>
			{% endfor %}
		</ul>
	</el-scrollbar>
	<el-upload
		class="upload-demo"
		action="/api/upload/cover"
		multiple
		:headers="avatar_list_headers"
		:before-upload="avatar_list_upload"
		:on-success="avatar_list_success"
		list-type="picture">
		<el-button size="small" type="primary">点击上传</el-button>
		<div slot="tip" class="el-upload__tip">只能上传jpg/png文件，且不超过2M</div>
	</el-upload>
{% endblock %}
{% block js %}
	<script src="/static/viewer/js/viewer.js"></script>
	<script>
		$('.cover_list>li').viewer({
		})
	</script>
{% endblock %}

templates/backend/edit_article.html
{% extends 'backend/add_article.html' %}
{% block btn %}
	<el-button
		type="danger"
		@click="add_drawer=true"
		id="edit_info"
		data_title="{{ article_obj.title }}"
		data_abstract="{{ article_obj.abstract }}"
		data_pwd="{{ article_obj.pwd }}"
		data_category="{{ article_obj.category }}"
		data_tags="{{ tags }}"
		data_cover_url="{{ article_obj.cover.url.url }}"
		data_cover_id="{{ article_obj.cover.nid }}"
		data_recommend="{{ article_obj.recommend }}"
	>编辑文章信息
	</el-button>
{% endblock %}

{% block drawer %}
	<el-drawer
		title="编辑文章"
		:visible.sync="add_drawer"
		direction="rtl">
		<div class="add_el_drawer_content">
			<el-collapse v-model="add_article_activeNames">
				<el-collapse-item title="文章标题" name="1">
					<el-input v-model="title" placeholder="文章标题"></el-input>
				</el-collapse-item>
				<el-collapse-item title="文章简介" name="2">
					<el-input
						type="textarea"
						:rows="5"
						resize="none"
						placeholder="请输入文章简介(默认截取正文前30字符)"
						v-model="abstract">
					</el-input>
				</el-collapse-item>
				<el-collapse-item class="category_tags" title="文章分类和标签" name="3">
					<el-select v-model="category_id" class="category" placeholder="请选择">
						{% for category in category_list %}
							<el-option
								label="{{ category.1 }}"
								value="{{ category.0 }}">
							</el-option>
						{% endfor %}
					</el-select>
					<el-select
						v-model="tags"
						multiple
						collapse-tags
						filterable
						allow-create
						default-first-option
						class="tags"
						style="margin-left: 20px;"
						placeholder="请选择文章标签">
						{% for tag in tag_list %}
							<el-option
								label="{{ tag.title }}"
								value="{{ tag.nid }}">
							</el-option>
						{% endfor %}
					</el-select>
				</el-collapse-item>
				<el-collapse-item title="文章封面" class="article_cover" name="4">
					<div class="left">
						{#						这里直接写出对应文章的封面#}
						<img src="" id="cover_img" style="height: 200px">
					</div>
					<div class="right">
						<el-select popper-class="select_cover" @change="edit_select_cover" v-model="cover_id" placeholder="请选择文章封面">
							{% for cover in cover_list %}
								<el-option
									label="{{ cover.url.url }}"
									value="{{ cover.nid }}">
									<img src="{{ cover.url.url }}" alt="">
								</el-option>
							{% endfor %}
						</el-select>
					</div>
				</el-collapse-item>
				<el-collapse-item class="can_choose" title="文章可选设置" name="5">
					<el-switch
						style="display: block"
						v-model="recommend"
						active-color="#13ce66"
						inactive-color="#ff4949"
						active-text="上推荐"
						inactive-text="不上推荐">
					</el-switch>
					<el-switch
						style="display: block"
						v-model="pwd_active"
						active-color="#13ce66"
						inactive-color="#ff4949"
						active-text="加密"
						inactive-text="不加密">
					</el-switch>
					<el-input v-show="pwd_active" v-model="pwd" placeholder="请输入文章加密密码"></el-input>
				</el-collapse-item>
			</el-collapse>
			<div class="article_btn_list">
				<el-button type="primary" @click="edit_article({{ article_obj.nid }})">确认修改</el-button>
			</div>
		</div>
	</el-drawer>
{% endblock %}

{% block textarea %}
	<textarea name="" id="" style="display: none">{{ article_obj.content }}</textarea>
{% endblock %}

templates/backend/reset_pwd.html
{% extends 'backend/backend.html' %}

{% block content %}

{% endblock %}