blogapi/urls.py
from django.urls import path, re_path
from blogapi.views import login, article, comment, mood, user, file, apiEmail, history, sites

app_name = 'blogapi'
urlpatterns = [
    path('login', login.LoginView.as_view(), name='login'),  # 登录
    path('sign', login.SignView.as_view(), name='sign'),  # 注册
    path('article', article.ArticleView.as_view(), name='article'),  # 发布文章
    path('article/<int:nid>', article.ArticleView.as_view(), name='article'),  # 修改文章
    # 查看加密文章
    path('articlePwd/<int:nid>', article.ArticlePwdView.as_view(), name='articlePwd'),
    re_path(r'article/comment/(?P<nid>\d+)', comment.CommentView.as_view(), name='comment'),  # 发布评论
    # 评论点赞
    re_path('comment/digg/(?P<nid>\d+)', comment.CommentDiggView.as_view(), name='comment_digg'),
    # 文章点赞
    re_path('article/digg/(?P<nid>\d+)', article.ArticleDiggView.as_view(), name='article_digg'),
    # 文章收藏
    re_path('article/collect/(?P<nid>\d+)', article.ArticleCollectsView.as_view(), name='article_collect'),
    # 文章封面修改
    path('article/cover/<int:nid>', article.EditArticleCoverView.as_view(), name='EditArticleCover'),
    # 心情路由
    path('mood', mood.MoodView.as_view(), name='mood'),
    re_path(r'mood/(?P<nid>\d+)', mood.MoodView.as_view(), name='mood_delete'),  # 删除心情
    re_path(r'mood_comment/(?P<nid>\d+)', mood.MoodCommentView.as_view(), name='mood_comment_edit'),  # 修改心情
    # 修改密码
    path('edit_password', user.EditPasswordView.as_view(), name='editPassword'),
    # 修改头像
    path('change_avatar', user.EditAvatarView.as_view(), name='editAvatar'),
    path('upload/avatar', file.AvatarUploadView.as_view(), name='AvatarUpload'),
    path('upload/avatar/<int:nid>', file.AvatarUploadView.as_view(), name='AvatarDelete'),
    path('upload/cover', file.CoverUploadView.as_view(), name='CoverUpload'),
    path('upload/cover/<int:nid>', file.CoverUploadView.as_view(), name='CoverDelete'),
    # 粘贴上传
    path('paste_upload', file.PasteUploadView.as_view(), name='pasteUpload'),
    path('sendEmail', apiEmail.ApiEmailView.as_view(), name='sendEmail'),
    path('perfectInformation', user.EditUserInfoView.as_view(), name='perfectInformation'),
    path('cancelCollection', user.CancelCollectionView.as_view(), name='cancelCollection'),  # 取消收藏
    # 回忆录
    # 发布记录
    path('history/', history.HistoryView.as_view(), name='history'),
    # 编辑记录
    path('history/<int:nid>', history.HistoryView.as_view(), name='history'),
    # 网站导航
    # 添加网站标签
    path('addSiteTag/', sites.NavTagsView.as_view(), name='addSiteTag'),
    path('addSiteTag/<int:nid>', sites.NavTagsView.as_view(), name='EditOrDeleteSiteTag'),
    # 获取网站数据列表
    path('sites/', sites.NavView.as_view(), name='sites'),
    # 编辑网站数据
    path('sites/<int:nid>', sites.NavView.as_view(), name='EditSites'),
    # 用于动态获取网站标签
    path('siteTag', sites.NavTagView.as_view(), name='SiteTag'),
    # 网站点赞
    path('siteDigg/<int:nid>', sites.NavDiggView.as_view(), name='SiteDigg'),
    # 网站收藏
    path('siteCollect/<int:nid>', sites.NavCollectsView.as_view(), name='siteCollect'),
    # 意见反馈
    path('feedback', user.FeedBackView.as_view(), name='feedback'),
]

fengfengzhidao/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog01.urls')),
    path('api/', include('blogapi.urls')),
    # media配置
    # serve 静态文件开发试图 只用于本地开发 不推荐生产环境
    # 用户上传文件路由配置
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

blog01/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.html import format_html
from django.db.models.signals import pre_delete  # 删除文件
from django.dispatch.dispatcher import receiver  # 删除文件
from blogapi.utils.get_location_info import get_addr_ip, get_ip


# Create your models here.
# 网站信息表
class Site(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='网站标题')
    abstract = models.CharField(max_length=128, verbose_name='网站简介')
    key_words = models.CharField(max_length=128, verbose_name='网站关键字')
    record = models.CharField(max_length=32, verbose_name='网站备案号')
    create_date = models.DateTimeField(verbose_name='建站日期')
    version = models.CharField(max_length=16, verbose_name='网站版本号')
    icon = models.FileField(verbose_name='网站图标', upload_to='site_icon/')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '网站信息'


# 个人信息
class MyInfo(models.Model):
    nid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32, verbose_name='名字')
    job = models.CharField(max_length=128, verbose_name='工作')
    email = models.EmailField(max_length=64, verbose_name='邮箱')
    site_url = models.CharField(max_length=32, verbose_name='网站链接')
    addr = models.CharField(max_length=16, verbose_name='地址')
    bilibili_url = models.URLField(verbose_name='哔哩哔哩链接')
    github_url = models.URLField(verbose_name='GitHub链接')
    wechat_img = models.FileField(verbose_name='微信图片', upload_to='my_info/')
    qq_img = models.FileField(verbose_name='QQ图片', upload_to='my_info/')

    class Meta:
        verbose_name_plural = '个人信息'


# 用户表
class UserInfo(AbstractUser):
    """
    继承与django自带的User字段 并且需要在settings里面将自带的字段指向到这个字段
    """
    nid = models.AutoField(primary_key=True)
    sign_choice = (
        (0, '用户名注册'),
        (1, '手机号注册'),
        (2, '邮箱注册'),
        (3, 'QQ注册'),
    )
    nick_name = models.CharField(max_length=16, verbose_name='昵称', null=True, blank=True)
    # avatar_url = models.URLField(verbose_name='用户真实头像地址', null=True)
    sign_status = models.IntegerField(default=0, choices=sign_choice, verbose_name='注册方式')
    tel = models.CharField(verbose_name='手机号', max_length=12, null=True, blank=True)
    integral = models.IntegerField(default=20, verbose_name='用户积分')
    # 这个是做前后端分离的时候使用的
    # token = models.CharField(verbose_name="TOKEN", max_length=64, null=True, blank=True)
    avatar = models.ForeignKey(
        to='Avatars',
        to_field='nid',
        on_delete=models.SET_NULL,
        verbose_name='用户头像',
        null=True
    )
    collects = models.ManyToManyField(
        to='Articles',
        verbose_name='收藏的文章',
        blank=True,
    )

    navs = models.ManyToManyField(
        to='Navs',
        verbose_name='收藏的网站',
        blank=True
    )

    class Meta:
        verbose_name_plural = '用户'


# 用户头像表
class Avatars(models.Model):
    nid = models.AutoField(primary_key=True)
    # 这里的FileField模型需要在settings中设置文件上传路径
    # 需要定义MEDIA_ROOT作为 Django 存储上传文件的目录的完整路径
    # 还要定义 MEDIA_URL 作为该目录的基本公共 URL。确保这个目录是 Web 服务器的用户账号可以写的
    # 这里的上传地址后面还可以尝试使用strftime()格式  upload_to='path/%Y/%m/%d'
    # 比如 在 2007 年 1 月 15 日上传了一个文件，它将被保存在 /home/media/photos/2007/01/15 目录下
    url = models.FileField(verbose_name='用户头像地址', upload_to='avatars/')

    def __str__(self):
        return str(self.url)

    class Meta:
        verbose_name_plural = '用户头像'


@receiver(pre_delete, sender=Avatars)  # sender=你要删除或修改文件字段所在的类**
def avatar_delete(instance, **kwargs):  # 函数名随意
    # print('进入文件删除方法，删的是', instance.url)  # 用于测试
    instance.url.delete(False)  # file是保存文件或图片的字段名**


# 文章表
class Articles(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标题', max_length=32, null=True, blank=True)
    abstract = models.CharField(verbose_name='文章简介', max_length=128, null=True, blank=True)
    content = models.TextField(verbose_name='文章内容', null=True, blank=True)
    create_date = models.DateTimeField(verbose_name='文章发布日期', auto_now_add=True, null=True)
    change_date = models.DateTimeField(verbose_name='文章修改日期', auto_now=True, null=True)
    status_choice = (
        (0, '未发布'),
        (1, '已发布'),
    )
    status = models.IntegerField(verbose_name='文章保存状态', choices=status_choice)
    recommend = models.BooleanField(verbose_name='是否上推荐', default=True)
    cover = models.ForeignKey(
        to='Cover',
        to_field='nid',
        on_delete=models.SET_NULL,
        verbose_name='文章封面', null=True, blank=True
    )
    look_count = models.IntegerField(verbose_name='文章阅读量', default=0)
    comment_count = models.IntegerField(verbose_name='文章评论量', default=0)
    digg_count = models.IntegerField(verbose_name='文章点赞量', default=0)
    collects_count = models.IntegerField(verbose_name='文章收藏数', default=0)
    category_choice = (
        (1, '前端'),
        (2, '后端'),
        (3, '项目相关')
    )
    category = models.IntegerField(verbose_name='文章分类', choices=category_choice, null=True, blank=True)
    tag = models.ManyToManyField(
        to='Tags',
        verbose_name='文章标签',
        blank=True
    )
    pwd = models.CharField(max_length=32, verbose_name='文章密码', null=True, blank=True)
    author = models.CharField(max_length=16, verbose_name='作者', null=True, blank=True)
    source = models.CharField(max_length=32, verbose_name='来源', null=True, blank=True)
    link = models.URLField(verbose_name='文章链接', null=True, blank=True)
    word = models.IntegerField(verbose_name='文章字数', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '文章'


# 评论表
class Comment(models.Model):
    nid = models.AutoField(primary_key=True)
    digg_count = models.IntegerField(verbose_name='点赞', default=0)
    article = models.ForeignKey(verbose_name='评论文章', to='Articles', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE, null=True)
    content = models.TextField(verbose_name='评论内容')
    comment_count = models.IntegerField(verbose_name='子评论数', default=0)
    drawing = models.TextField(verbose_name='配图', null=True, blank=True)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 链接到自己  当父评论消失之后 子评论也跟着消失
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='是否是父评论')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = '评论'


# 新闻的爬取记录
class New(models.Model):
    nid = models.AutoField(primary_key=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='获取时间')

    class Meta:
        verbose_name_plural = '新闻爬取'


# 文章封面
class Cover(models.Model):
    nid = models.AutoField(primary_key=True)
    url = models.FileField(verbose_name='文章封面地址', upload_to='article_img/')

    def __str__(self):
        return str(self.url)

    class Meta:
        verbose_name_plural = '文章封面'


@receiver(pre_delete, sender=Cover)  # sender=你要删除或修改文件字段所在的类**
def cover_delete(instance, **kwargs):  # 函数名随意
    # print('进入文件删除方法，删的是', instance.url)  # 用于测试
    instance.url.delete(False)  # file是保存文件或图片的字段名**


# 标签表
class Tags(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=16, verbose_name='标签名字')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '文章标签'


# 回忆录
class History(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='事件名称')
    content = models.TextField(verbose_name='事件内容')
    create_date = models.DateField(verbose_name='创建时间', null=True)
    drawing = models.TextField(verbose_name='配图组，以;隔开', null=True, blank=True)

    class Meta:
        verbose_name_plural = '回忆录'


# 心情
class Moods(models.Model):
    nid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='发布人', max_length=16)
    create_date = models.DateTimeField(verbose_name='发布时间', auto_now=True)
    content = models.TextField(verbose_name='心情内容')
    ip = models.GenericIPAddressField(verbose_name='ip地址', default='127.0.0.1')
    addr = models.JSONField(verbose_name='用户地址信息',  null=True)
    drawing = models.TextField(verbose_name='配图组，以;隔开', null=True, blank=True)
    comment_count = models.IntegerField(verbose_name='评论数', default=0)
    digg_count = models.IntegerField(verbose_name='点赞数', default=0)
    avatar = models.ForeignKey(
        to='Avatars',
        to_field='nid',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='心情的发布头像'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '心情'


# 心情评论
class MoodComment(models.Model):
    nid = models.AutoField(primary_key=True)
    avatar = models.ForeignKey(
        to='Avatars',
        to_field='nid',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='心情的发布头像'
    )
    name = models.CharField(verbose_name='评论人', max_length=16, null=True)
    content = models.TextField(verbose_name='评论内容')
    digg_count = models.IntegerField(verbose_name='点赞数', default=0)
    ip = models.GenericIPAddressField(verbose_name='ip地址', default='127.0.0.1')
    addr = models.JSONField(verbose_name='用户地址信息',  null=True)
    mood = models.ForeignKey(
        to='Moods',
        to_field='nid',
        on_delete=models.SET_NULL,
        verbose_name='评论的心情',
        null=True
    )
    create_date = models.DateTimeField(
        verbose_name='评论时间', auto_now=True
    )

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = '心情评论'


# 网站导航
class Navs(models.Model):
    nid = models.AutoField(primary_key=True)
    # nav_category = models.ForeignKey(
    #     to='NavCategory',
    #     to_field='nid',
    #     on_delete=models.SET_NULL,

blog01/views/backend.py
from django.shortcuts import render, redirect

from blog01.models import *
from blogapi.utils.permissions_control import is_super_fun




# Create your views here.
def backend(request):
    if not request.user.username:
        # 没有登录
        return redirect('/')
    user = request.user
    collect_query = user.collects.all()
    return render(request, 'backend/backend.html', locals())


@is_super_fun
def add_article(request):
    # 拿到所有的分类，标签
    tag_list = Tags.objects.all()
    # 拿到所有的文章封面
    cover_list = Cover.objects.all()
    category_list = Articles.category_choice
    print(category_list)
    return render(request, 'backend/add_article.html', locals())


# 编辑头像
def change_avatar(request):
    avatar_url = request.user.avatar.url.url
    avatar_list = Avatars.objects.all()
    for i in avatar_list:
        if i.url.url == avatar_url:
            avatar_id = i.nid
    return render(request, 'backend/change_avator.html', locals())


def reset_pwd(request):
    return render(request, 'backend/reset_pwd.html', locals())


@is_super_fun
def edit_article(request, nid):
    article_obj = Articles.objects.get(nid=nid)  # 获取到对应的文章
    tags = [str(tag.nid) for tag in article_obj.tag.all()]  # 拿到已经选择的标签
    tag_list = Tags.objects.all()
    cover_list = Cover.objects.all()  # 获取所有的封面
    category_list = Articles.category_choice
    return render(request, 'backend/edit_article.html', locals())


@is_super_fun
def admin_home(request):
    return render(request, 'backend/admin/admin_home.html')


# 头像列表
@is_super_fun
def avatar_list(request):
    avatar_all = Avatars.objects.all()
    return render(request, 'backend/avatar_list.html', locals())


# 文章封面
@is_super_fun
def cover_list(request):
    cover_query = Cover.objects.all()
    return render(request, 'backend/cover_list.html', locals())

blogapi/views/history.py
from django.views import View
from django.http import JsonResponse
from blog01.models import Avatars, Cover, UserInfo, History
from django import forms
from blogapi.views.login import clean_form
from datetime import date, datetime


class HistoryForm(forms.Form):
    title = forms.CharField(error_messages={'required': '请输入事件标题'})
    content = forms.CharField(error_messages={'required': '请输入事件内容'})
    create_date = forms.CharField()
    drawing = forms.CharField(required=False)

    def clean_create_date(self):
        create_date = self.cleaned_data['create_date']
        if not create_date:
            create_date = date.today()
        else:
            create_date = datetime.strptime(create_date.split('T')[0], '%Y-%m-%d').date()
        return create_date


class HistoryView(View):
    def post(self, request, **kwargs):
        res = {
            'msg': '记录发布成功',
            'code': 0,
            'self': None
        }
        data = request.data
        form = HistoryForm(data)
        if not form.is_valid():
            res['self'], res['msg'] = clean_form(form)
            res['code'] = -1
            return JsonResponse(res)
        nid = kwargs.get('nid')
        if nid:
            # 编辑操作
            history_query = History.objects.filter(nid=nid)
            history_query.update(**form.cleaned_data)
            res['msg'] = '记录编辑成功'
        else:
            History.objects.create(**form.cleaned_data)
        return JsonResponse(res)

    def delete(self, request, nid):
        res = {
            'msg': '记录删除成功',
            'code': 0,
        }
        if not request.user.is_superuser:
            res['msg'] = '用户验证失败`'
            res['code'] = -1
            return JsonResponse(res)
        history_query = History.objects.filter(nid=nid)
        history_query.delete()
        return JsonResponse(res)

templates/blog01/about.html
{% extends 'blog01/index.html' %}

{% load my_tag %}

{% block banner %}
	{% banner 'about' %}
{% endblock %}

templates/blog01/article_lock.html
{% extends 'blog01/article.html' %}

{% block css %}
	<style>
        .article {
            width: 300px;
        }

        .article > .title {
            text-align: center;
        }

        .article > div {
            margin-bottom: 10px;
        }

        .article > .el-button {
            width: 100%;
        }
	</style>
{% endblock %}

{% block main %}
	<div class="slide_bar" ref="slider" style="display: none;">
		<div class="title">
			<span>开启悬浮目录</span>
			<el-switch
				v-model="isShowSlider"
				active-color="#13ce66"
				inactive-color="#ff4949"
				@change="sliderChange">
			</el-switch>
		</div>
		<div class="body">
			<p :tagName="item.tagName" @click="goToPosition(item.pos, $event)" v-for="(item, index) in slide_list"
			   :key="index">
				[[item.c]]
			</p>
		</div>
	</div>
	<div class="article">
		<div class="title">
			该内容需要输入密码查看
		</div>
		<el-input
			id="article_pwd"
			v-model="article_pwd"
			placeholder="请输入文章密码">
		</el-input>
		<el-button type="primary" @click="article_pwd_show('{{ article_obj.nid }}')">查看</el-button>
	</div>
{% endblock %}

{% block article_js %}
	<script>
        setTimeout(() => {
            $('.slider_bar').remove()
        }, 350)
	</script>
{% endblock %}

templates/blog01/history.html
{% extends 'blog01/index.html' %}

{% load my_tag my_filter %}
{% block css %}
	<link rel="stylesheet" href="/static/viewer/css/viewer.css">
	<link rel="stylesheet" href="/static/blog01/css/history.css">
{% endblock %}
{% block banner %}
	{% banner 'history' %}
{% endblock %}
{% block main %}
	<div class="main">
		<el-dialog
			:title="history_edit_add?'事件编辑':'事件添加'"
			:visible.sync="history_dialogVisible"
			width="40%"
			:before-close="history_handleClose">
			<div class="dialog_content">
				<div>
					<label for="">事件标题</label>
					<el-input v-model="history.title" placeholder="请输入事件标题"></el-input>
				</div>
				<div>
					<label for="">事件时期</label>
					<el-date-picker
						v-model="history.create_date"
						type="date"
						value-format="yyyy-MM-dd"
						:picker-options="history_pickerOption"
						placeholder="选择日期">
					</el-date-picker>
				</div>
				<div>
					<label for="">事件内容</label>
					<el-input
						type="textarea"
						:rows="4"
						placeholder="请输入事件内容"
						resize="none"
						v-model="history.content">
					</el-input>
				</div>
				<div >
					<label for="">事件配图</label>
					<textarea
						rows="10"
						class="drawing"
						type="textarea"
						placeholder="请输入事件配图组"
						@paste="paste_upload"
						v-model="history.drawing">
					</textarea>
				</div>
				<div class="drawing_show">
					<img :src="url" v-for="(url, index) in history_show_drawing" :key="index">
				</div>
			</div>
			<span slot="footer" class="dialog-footer">
            <el-button @click="history_dialogVisible = false">取 消</el-button>
            <el-button type="primary" @click="history_add_method(history_edit_add)">确 定</el-button>
			</span>
		</el-dialog>
		{% if request.user.is_superuser %}
			<h2 class="title cursor" @click="history_dialogVisible=true">君安小窝回忆录</h2>
		{% else %}
			<h2 class="title">君安小窝回忆录</h2>
		{% endif %}
		<ul class="timeline-wrapper">
			{% for history in history_list %}
				<li class="timeline-item">
				<div class="timeline-box">
					<div class="out-circle">
						{% if request.user.is_superuser %}
							<div class="in-circle cursor super" @click="history_remove('{{ history.nid }}', $event)"></div>
						{% else %}
							<div class="in-circle"></div>
						{% endif %}
					</div>
					<div class="long-line"></div>
				</div>
				<div class="timeline-content">
					{% if request.user.is_superuser %}
						<div content="{{ history.content }}" drawing="{{ history.drawing }}" @click="history_edit_show($event,'{{ history.nid }}', '{{ history.title }}','{{ history.create_date|date:'Y-m-d' }}')" class="timeline-date cursor">{{ history.create_date|date:'Y-m-d' }}</div>
					{% else %}
						<div class="timeline-date">{{ history.create_date|date:'Y-m-d' }}</div>
					{% endif %}
					<div class="timeline-title">{{ history.title }}</div>
					<ul class="timeline-desc">
						{% generate_content history.content  %}
					</ul>
					<div class="peitu">
						<div>
							{% generate_drawing history.drawing %}
						</div>
					</div>
				</div>
			</li>
			{% endfor %}
		</ul>
	</div>


{% endblock %}

{% block article_js %}
	<script src="/static/viewer/js/viewer.js"></script>
	<script>
	$('.peitu>div').viewer()
	</script>
{% endblock %}

templates/blog01/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% block title %}
		<title>登录</title>
	{% endblock %}
	<link rel="stylesheet" href="{% static 'blog01/css/restart.css' %}">
	<link rel="stylesheet" href="{% static 'blog01/css/login.css' %}">
	<!-- 引入样式 -->
	<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
	{#	<script src="{% static 'blog01/js/jquery/jquery.min.js' %}"></script>#}
	<script src="{% static 'blog01/js/axios/axios.min.js' %}"></script>
	{#	<script src="{% static 'blog01/vue/vue.js' %}"></script>#}
	<script src="/static/blog01/vue/vue.js"></script>
	<script src="https://cdn.bootcss.com/qs/6.7.0/qs.min.js"></script>
	<!-- 引入组件库 -->
	<script src="https://unpkg.com/element-ui/lib/index.js"></script>
</head>
<body>
<div id="app">
	<main>
		<div class="top">
			<div class="title">
				{% block main_title %}
					<a href="{% url 'blogapi:login' %}" class="active">登录</a>
					<a href="{% url 'blogapi:sign' %}">注册</a>
				{% endblock %}
			</div>
			<div class="login_form">
				{% csrf_token %}
				{% block form %}
					<input type="text" ref="login_form_name"  v-model="login_form.name" placeholder="用户名/邮箱">
					<input type="password"  ref="login_form_pwd" v-model="login_form.pwd" placeholder="密码">
					<div class="code">
						<input type="text"  ref="login_form_code" v-model="login_form.code"  placeholder="验证码">
						<img @click="get_random_code($event)" src="{% static 'blog01/img/login/code.png' %}" alt="">
					</div>
					<button @click="login">登录</button>
				{% endblock %}
			</div>
			<div class="other_login">
				<p>其他登录方式</p>
				<div>
					<img src="{% static 'blog01/img/footer/qq_icon.svg' %}" alt="">
					<img src="{% static 'blog01/img/footer/wexin_icon.svg' %}" alt="">
					<img src="{% static 'blog01/img/footer/weibo_icon.svg' %}" alt="">
				</div>
			</div>
		</div>
		<div class="bottom">
			<img src="{% static 'blog01/img/login/year_2022_uci7.svg' %}" alt="">
		</div>
	</main>
</div>
<script>
    // 请求中间件
    axios.interceptors.request.use(request=>{
        if(request.method === 'post'){
            console.log('axios请求')
            let csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value
            request.headers['X-CSRFToken'] = csrftoken
        }
        return request
    })
    // 响应中间件
    axios.interceptors.response.use(response=>{
        return response.data
    })
    new Vue({
        el:"#app",
        data:{
            login_form:{
                name:'',
                pwd:'',
                code:'',
            },
            sign_form:{
                name:'',
                pwd:'',
                repwd:'',
                code:'',
            },
        },
        methods:{
            login(){
                axios.post("{% url 'blogapi:login' %}", this.login_form).then(res=>{
                    if(res.code){
                        // 验证失败的
                        this.$message.error(res.msg)
                        this.$refs[`login_form_${res.self}`].focus()
                    }else{
                        this.$message.success(res.msg)
	                    setTimeout(()=>{
                            location.href = "{% url 'blog01:index' %}"
	                    }, 1000)
                    }
                })
            },
            sign(){
                axios.post("{% url 'blogapi:sign' %}", this.sign_form).then(res=>{
                    if(res.code){
                        // 验证失败的
                        this.$message.error(res.msg)
                        this.$refs[`sign_form_${res.self}`].focus()
                    }else{
                        this.$message.success(res.msg)
	                    setTimeout(()=>{
                            location.href = "{% url 'blog01:index' %}"
	                    }, 1000)
                    }
                })
            },
	        get_random_code(e){
		        let date = new Date().getTime()
		        e.target.src = "/login/verify_code?timestamp="+date
            },
        }
    })
</script>
</body>
</html>